spring:
  #数据源基本配置
  datasource:
    username: root
    password: 1MhJK1tH9n60g1&L9Lqm
    url: jdbc:mysql://45.40.206.174:3306/mpmalluser?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name:
    # 指定自定义的数据库连接池替换默认的
    type: com.alibaba.druid.pool.DruidDataSource
    # druid数据源其他的配置
    initialSize: 1
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # redis
  ## Redis数据库索引（默认为0）
  redis:
    database: 0
    ## Redis服务器地址
    host: 45.40.206.174
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: 39icRSqI0ccYWwxRfXmd3BZjLN6i6Sp0
    ## 连接超时时间（毫秒）
    timeout: 10000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 100
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      ## 连接池中的最大空闲连接
      max-idle: 10
      ## 连接池中的最小空闲连接
      min-idle: 1
  output:
    ansi:
      enabled: always
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.chouchongkeji.dial.pojo
yichen:
  security:
    ##验证码的有效时间
    smscode:
      length: 7
      expire: 180
      urls:
        - {url: /noauth/user/bindPhone, type: 1}
        - {url: /auth/user/find/pwd, type: 2}
        - {url: /auth/user/modify_phone, type: 3}
        - {url: /auth/receive/item/order_wx, type: 4}
    ##配置客户端信息
    oauth2:
      client:
        - {clientId: giftcircler-dl,clientSecret: qMEjFl8w63EtAX17cRX83L0iMkK2U4mg,accessTokenValidityTime: 6592000}
    # 配置接口签名
    sign:
      needSign: true
      urls:
        - /noauth/pay/**
        - /druid/**
        - /noauth/file/**
        - /noauth/item/html_detail
        - /noauth/v1/article/html
    # 重复请求过滤接口
    request:
      url:
        - /auth/v1/bp/list
        - /auth/moment/list
        - /auth/item/order/list
        - /auth/user/profile
        - /auth/user/gift/preference/list
        - /auth/user/info
        - /auth/user/tag/userList
        - /auth/v1/wallet/detail
        - /auth/v1/bankCard/bankList
        - /auth/v1/bankCard/list
        - /auth/v1/withdraw/list
        - /auth/v1/wallet/earn_record
        - /auth/v1/reAddress/list
        - /auth/v1/reAddress/detail
        - /auth/v1/favorite/itemList
        - /auth/search/all_list
        - /auth/cart/list
        - /auth/friend/notifyMsgs
        - /auth/friend/group/list
        - /auth/friend/list
        - /auth/friend/count
        - /auth/moment/detail
        - /auth/moment/list/self
        - /auth/receive/item/list
        - /auth/receive/item/detail
        - /auth/v1/withdraw/wxRecords
        - /auth/friend/bp/list
        - /auth/friend/bp/detail
        - /auth/friend/bp/record_list
        - /auth/event/list
        - /auth/v1/gift_send/send_list
        - /auth/v1/message/home
        - /auth/v1/message/list
        - /auth/memo/affair/home
        - /auth/welfare/list
        - /auth/memo/affair2/event/list
        - /auth/memo/affair2/list
        - /auth/memo/affair2/list/friend
        - /auth/memo/affair2/festival_detail
        - /auth/memo/affair2/festival_item
        - /auth/memo/affair2/friend_list
        - /auth/moment/count
        - /auth/v1/fireworks/detail
        - /auth/v1/fireworks/user_list
        - /auth/v1/fireworks/earn_record
    # 图片地址拼接
    image:
      needSplice: true
      host: https://liyuquan.cn/static
  service:
    host: https://liyuquan.cn/app/
    productDetail: https://liyuquan.cn/static/product.html?uid=
    articleDetail: https://liyuquan.cn/static/article.html?uid=

#    logo: http://43.241.223.169:800/image/logo.jpg
server:
  port: 8088


logging:
  level:
    com:
      chouchongkeji:
        dial:
          dao: debug

